version: '3'

vars:
  SRC_DIR: "./src"
  TEST_DIR: "./tests"

tasks:
  default:
    cmds:
      - uv run ruff check {{.SRC_DIR}} {{.TEST_DIR}}
      - uv run ruff format --check {{.SRC_DIR}} {{.TEST_DIR}}
      - uv run mypy --strict --ignore-missing-imports {{.SRC_DIR}} {{.TEST_DIR}}
      - uv run pytest {{.TEST_DIR}}
    silent: false
  pre-commit-checks:
    desc: "Run all pre-commit quality checks"
    cmds:
      - uv run ruff check --force-exclude {{.SRC_DIR}} {{.TEST_DIR}}
      - uv run ruff format --force-exclude --check {{.SRC_DIR}} {{.TEST_DIR}}
      - uv run mypy --strict --ignore-missing-imports {{.SRC_DIR}} {{.TEST_DIR}}
    silent: false
  clean:
    desc: "Clean up build artifacts"
    cmds:
      - rm -rf ./dist
      - rm -f .coverage
      - find . \(
          -name '__pycache__' 
          -o -name '.pytest_cache' 
          -o -name '.mypy_cache' 
          -o -name '.ruff_cache' 
        \) -type d -exec rm -r {} +
    silent: true
